import type { NextPage } from 'next';
import Head from 'next/head';

import ROOT_DATA from '../data';
import { CURRENT_YEAR } from '../configs';
import { getStatByYear } from '../utils';

import Layout from '../components/Layout';
import { Segment, Button, Divider } from 'semantic-ui-react';
import useUrlQuery from '../hooks/useUrlQuery';

type StatByPeriod = Record<Period, StatData>;

interface Props {
  data: StatByPeriod;
}

const PERIOD_TYPES: Period[] = ['올해', '최근 3년', '최근 5년', '최근 10년'];
const DEFAULT_PERIOD: Period = '올해';

const GENDER_TYPES: Gender[] = ['M', 'F'];
const DEFAULT_GENDER: Gender = 'M';

const IndexPage: NextPage<Props> = ({ data }) => {
  const { parsedValues, updateQuery } = useUrlQuery({
    defaultValues: { period: DEFAULT_PERIOD, gender: DEFAULT_GENDER },
  });

  const getHandleGenderChange = (gender: Gender) => () => {
    updateQuery({ key: 'gender', value: gender });
  };

  const getHandlePeriodChange = (period: Period) => () => {
    updateQuery({ key: 'period', value: period });
  };

  const period = parsedValues['period'] as Period;
  const gender = parsedValues['gender'] as Gender;

  const Genders = (
    <Button.Group basic size="small">
      {GENDER_TYPES.map((v) => (
        <Button
          key={v}
          active={v === gender}
          onClick={getHandleGenderChange(v)}
        >
          {v === 'M' ? '남자' : '여자'}
        </Button>
      ))}
    </Button.Group>
  );

  const PeriodButtons = (
    <Button.Group basic size="small">
      {PERIOD_TYPES.map((v) => (
        <Button
          key={v}
          active={v === period}
          onClick={getHandlePeriodChange(v)}
        >
          {v}
        </Button>
      ))}
    </Button.Group>
  );

  const getDisplayStat = (gender: Gender) => {
    // TODO: Type Guard => display null? error?
    return (
      <div>
        {data[period][gender].map((v) => (
          <div key={v.name}>
            <span>{v.name} </span>
            <span>
              {v.count}
              {'명 '}
            </span>
            <span>
              {v.rank}
              {'위'}
            </span>
          </div>
        ))}
      </div>
    );
  };

  return (
    <>
      <Head>
        {/* TODO: Add more metadata */}
        <title>
          이름 순위 | {period} 가장 많았던{' '}
          {gender === 'M' ? '남자 이름' : '여자 이름'}
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Segment size="mini">
          {Genders}
          <Divider />
          {PeriodButtons}
        </Segment>
        <div style={{ display: 'flex' }}>{getDisplayStat(gender)}</div>
      </Layout>
    </>
  );
};

export default IndexPage;

export async function getStaticProps() {
  const endYear = CURRENT_YEAR;

  const data: StatByPeriod = {
    올해: getStatByYear({ startYear: CURRENT_YEAR, endYear, data: ROOT_DATA }),
    '최근 3년': getStatByYear({
      startYear: CURRENT_YEAR - 2,
      endYear,
      data: ROOT_DATA,
    }),
    '최근 5년': getStatByYear({
      startYear: CURRENT_YEAR - 4,
      endYear,
      data: ROOT_DATA,
    }),
    '최근 10년': getStatByYear({
      startYear: CURRENT_YEAR - 9,
      endYear,
      data: ROOT_DATA,
    }),
  };
  return {
    props: {
      data,
    },
  };
}
