import type { NextPage } from 'next';
import Head from 'next/head';
import { ChangeEvent, useMemo, useState } from 'react';

import ROOT_DATA from '../data';
import { CURRENT_YEAR } from '../configs';
import { getStatByYear } from '../utils';

interface Props {
  data: RootData;
}

const RANK_TYPES: RankType[] = ['올해', '최근 3년', '최근 5년', '최근 10년'];

const Rank: NextPage<Props> = ({ data }) => {
  const [rankType, setRankType] = useState<RankType>('올해');

  const stat = useMemo(() => {
    let startYear: number;
    let endYear = CURRENT_YEAR;

    switch (rankType) {
      case '올해': {
        startYear = CURRENT_YEAR;
        break;
      }
      case '최근 3년': {
        startYear = CURRENT_YEAR - 2;
        break;
      }
      case '최근 5년': {
        startYear = CURRENT_YEAR - 4;
        break;
      }
      case '최근 10년': {
        startYear = CURRENT_YEAR - 9;
        break;
      }
      default: {
        startYear = CURRENT_YEAR;
      }
    }

    return getStatByYear({ startYear, endYear, data });
  }, [rankType, data]);

  const handleRankTypeChange = (e: ChangeEvent<HTMLSelectElement>) => {
    setRankType(e.target.value as RankType);
  };

  const rankTypeOptions = RANK_TYPES.map((v) => (
    <option key={v} value={v}>
      {v}
    </option>
  ));

  const getDisplayStat = (gender: Gender) => {
    return (
      <div>
        {stat[gender].map((v) => (
          <div key={v.name}>
            <span>{v.name} </span>
            <span>
              {v.count}
              {'명 '}
            </span>
            <span>
              {v.rank}
              {'위'}
            </span>
          </div>
        ))}
      </div>
    );
  };

  return (
    <div>
      <Head>
        <title>이름 순위</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <select value={rankType} onChange={handleRankTypeChange}>
          {rankTypeOptions}
        </select>
        <div style={{ display: 'flex' }}>
          {getDisplayStat('M')}
          {getDisplayStat('F')}
        </div>
      </main>
    </div>
  );
};

export default Rank;

export async function getStaticProps() {
  return {
    props: {
      data: ROOT_DATA,
    },
  };
}
