name: Update data every Monday
on:
  schedule:
    - cron: '0 6 * * 1' # Every monday at 06:00
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Change dir and install dependencies
        working-directory: crawler
        run: yarn install
      - name: Run script
        working-directory: crawler
        run: node index.js
      - name: Commit changes
        run: |
          git config --local user.email "sanginchun91@gmail.com"
          git config --local user.name "sanginchun"
          git add .
          git commit -m "update data $(date -u +'%Y-%m-%d')"
          git push
