name: Update data everyday
on:
  schedule:
    - cron: '0 12 * * *'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Change dir and install dependencies
        working-directory: crawler
        run: yarn install
      - name: Run script
        working-directory: crawler
        run: node index.js
      - name: Commit changes
        run: |
          git config --local user.email "sanginchun91@gmail.com"
          git config --local user.name "sanginchun"
          git add .
          git commit -m "Updated data"
          git push
